// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from "./Accordion/index.svelte";
import CaseStudies from "./CaseStudies/index.svelte";
import CtaBanner from "./CtaBanner/index.svelte";
import FeatureTrio from "./FeatureTrio/index.svelte";
import Hero from "./Hero/index.svelte";
import LeadText from "./LeadText/index.svelte";
import MediaText from "./MediaText/index.svelte";
import PageTitle from "./PageTitle/index.svelte";
import ProjectList from "./ProjectList/index.svelte";
import RichText from "./RichText/index.svelte";
import SectionGrid from "./SectionGrid/index.svelte";
import ServiceCards from "./ServiceCards/index.svelte";
import SplitHero from "./SplitHero/index.svelte";
import Steps from "./Steps/index.svelte";
import Testimonial from "./Testimonial/index.svelte";
import TextBlock from "./TextBlock/index.svelte";
import TextColumns from "./TextColumns/index.svelte";

export const components = {
  accordion: Accordion,
  case_studies: CaseStudies,
  cta_banner: CtaBanner,
  feature_trio: FeatureTrio,
  hero: Hero,
  lead_text: LeadText,
  media_text: MediaText,
  page_title: PageTitle,
  project_list: ProjectList,
  rich_text: RichText,
  section_grid: SectionGrid,
  service_cards: ServiceCards,
  split_hero: SplitHero,
  steps: Steps,
  testimonial: Testimonial,
  text_block: TextBlock,
  text_columns: TextColumns,
};
